# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d923855f505680b7f959530d6c37a5469b176f81893073804671653b8df90046b9dbed5aeb68421b3c67b84ba1935f08a3eda406e6717780e792238e80ee496

test:
  secret_key_base: ea646a49daa24aa3d0f956098fc59c984c7d5be2950219fd94f3429cb415d5db466d365da70082fc86438bfa3d5b9859a1c7e351499afbe6b7759ec72ecfd4bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
